version: "3.5"

services:
  dev-server:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      target: dev
    ports:
      - "4300:4300"
    volumes:
      - ..:/glowing-bear-src
    user: ${USER_GROUP:?}
    environment:
      - TI_ACCESS_TOKEN

  glowing-bear-medco:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      target: release
    ports:
      - "82:80"
    environment:
      - TI_ACCESS_TOKEN
      - GB_MEDCO_NODE_URL=http://localhost:3001
      - GB_KEYCLOAK_URL=http://localhost:8080/auth
      - GB_KEYCLOAK_REALM=ti-realm
      - GB_KEYCLOAK_CLIENT_ID=glowing-bear
      - GB_ONTOLOGY_SEARCH_LIMIT=30
      - GB_FOOTER_TEXT=
